### PR TITLE
added script to shutdown pc

### PR DESCRIPTION
**Pull request by vaibhavdaren**
#2 
added script to shutdown pc

### CODE REVIEW

**Comment by vaibhavdaren** [comment]
@drekhi12  any scripts ?

**Comment by drekhi12** [comment]
yes, a bit complex too though I'll accept this one too.

**Review by drekhi12 — CHANGES_REQUESTED** [review]
It is very distribution specific script, can you change the script because I tested it on my system and it didn't work.

**Review by vaibhavdaren — COMMENTED** [review]
changes done :)

**Comment by vaibhavdaren** [comment]
done 👍

**Pull request merged**
